### ISSUE TITLE
Increment or decrement the quantities in the cart.

### ISSUE THREAD

**Issue by vincenthfrance** [UraraReika/jet-woo-builder-custom-quantity-selectors#1]
I have a problem when I want to increment or decrement the quantities in the cart.

To reproduce this behavior,
Add 2 products in the basket.
Then starting from 0: do + until 5.
Do 2 times - (so qty =3) and when you do +, it subtracts.

I use the Astra theme.

Thanks in advance

**Comment by UraraReika** [comment]
Hello @vincenthfrance ! Thanks for the feedback.

This issue was fixed in the core of JetWoobuilder plugin and will be available in the next release.
