### ISSUE TITLE
Quantity Field Not Showing

### ISSUE THREAD

**Issue by GazDog** [UraraReika/jet-woo-builder-custom-quantity-selectors#2]
I have a problem on a site where the quantity field is not showing between the + and - Buttons

If you go to https://oldscotchathleticclub.com.au/shop/ and click on any item you will see, even after you select a size.

I have turned all plugins I could off and still no change. The product quantities are not limited. I have played around with CSS to see if that was the problem but still couldn't get anything. Also checked the console for JS errors but nothing.

That's about all I can figure out.

While the site is live the shop is not at the moment as it is still under development.

Cheers and thanks in advance
Garry

**Comment by UraraReika** [comment]
You need to setup correct fields width. For example set quantity field to 175px this is width for all this area - https://tppr.me/CzBbJ, and the decrease width on selectors controls - https://tppr.me/aog8l, because this is % width from the overall width of the area (25% times 2 from 175px)
